### ISSUE TITLE
sqelf container unstable.

### ISSUE THREAD

**Issue by svrooij** [datalust/sqelf#38]
I've been running both seq and sqelf in docker, separate containers. 

Sometimes I get the feeling that events from an other docker host don't reach seq anymore. A restart of the container running sqelf fixes the issue. It seems to crash but there isn't any message in the log.

Maybe there could be some kind of heartbeat functionality in the sqelf container, so that is can automatically restart when it hangs. The process doesn't seem to exit because that would stop the container (and them automatically reboot).

**Comment by nblumhardt** [comment]
Thanks for the note, @svrooij - we'll take a look and let you know what we come up with.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Gandelf is cool 🙂.

`sqelf` is a native Rust GELF server that's developed in this repo (not Ruby 😁). We kicked it off because we wanted to run the same code in a low-dependency Seq plug-in ([_Seq.Input.Gelf_}(https://nuget.org/packages/seq.input.gelf)), among other things.

Currently, the `run.sh` in the `sqelf` container's Dockerfile uses `exec` to swap out the initial `bash` process for `sqelf` - which won't necessarily cause the container to exit if the child `seqcli` process fails. We think we can improve on this by dropping the `exec` and setting the `pipefail` Bash option. Fingers crossed this will cause any process-level failures to propagate and get noticed by the host.

It's also possible that this issue is a hang or other kind of bug in `sqelf` or `seqcli` - if so, we'll be on the case and try to track it down.

Cheers,
Nick

**Comment by KodrAus** [comment]
We've just published a new version of the Docker container as `datalust/sqelf:1.0.205`. This includes some changes to the `run.sh` script so that if either side of the pipe fails we'll exit the container with a non-zero code.

**Comment by nblumhardt** [comment]
I think we should close this and see how the newer version goes in the wild - please let us know if you decide to redeploy it, @svrooij - thanks!

**Comment by svrooij** [comment]
@nblumhardt I've redeployed it and it's running the logs of a few containers. Will let you guys know if the stability changed.

**Comment by nblumhardt** [comment]
Awesome, thanks @svrooij 👍
