### ISSUE TITLE
GELF processing failed - "invliad type: string expected f64" when sending log event from Tomcat 8.5

### ISSUE THREAD

**Issue by macaustreet1** [datalust/sqelf#57]
Hi,

We are getting the following error when sending Tomcat log event to Seq via GELF Input app in Seq:
![image](https://user-images.githubusercontent.com/9262048/68554391-ddf82a00-0473-11ea-9f42-df1b5bf548f4.png)

Here is the log event output by Tomcat:
![image](https://user-images.githubusercontent.com/9262048/68554414-08e27e00-0474-11ea-9cc0-d4ab6dc1f613.png)

Settings in logging.properties:
![image](https://user-images.githubusercontent.com/9262048/68554617-1815fb80-0475-11ea-8de6-59739c881e83.png)

Settings in GELF input:
![image](https://user-images.githubusercontent.com/9262048/68554664-74791b00-0475-11ea-9efd-203ac752ca45.png)

Seq version: 5.1.3200
GELF Input version: 2.0.258-dev
logstash-gelf version: 1.13.0

**Comment by KodrAus** [comment]
Hi @macaustreet1 :wave:

Thanks for reaching out! I think the problem here is that the `timestamp` in the message is being sent as a `string` as per GELF 1.0, rather than as a `number` as per GELF 1.1. The Seq Input only supports the GELF 1.1 format. Do you know if your Logstash GELF plugin is configured for a particular version of the format?

**Comment by macaustreet1** [comment]
Thanks for the quick response KodrAus!

Yes you re right. The issue is from the GelfLogHandler version.

The issue is gone after i added the following lines into the config:
`biz.paluch.logging.gelf.jul.GelfLogHandler.version=1.1
biz.paluch.logging.gelf.jul.GelfLogHandler.timestampPattern=yyyy-MM-dd HH:mm:ss,SSS`
